import type { IngestPayloadDto } from "./businessFoundation";

export const businessFoundationSeedFixture: IngestPayloadDto = {
  connectorId: "connector_tmall_jewelry_demo",
  collectedAt: "2026-05-24T10:00:00.000Z",
  rows: [
    {
      platform: "tmall",
      storeId: "ctf-flagship",
      externalSkuId: "gold-ring-001",
      productName: "足金999古法莲花戒指 5.2g",
      category: "黄金饰品",
      brand: "周大福",
      sourceUrl: "https://demo.tmall.test/jewelry/gold-ring-001",
      rowIndex: 1,
      sales30d: 386,
      positiveRate: 0.982,
      stock: 168,
      originalPrice: 3899,
      lowestPrice30d: 3599,
      campaignPrice: 3499,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { material: "Au999", weight: "5.2g", certificate: "国检证书已上传" },
    },
    {
      platform: "tmall",
      storeId: "ctf-flagship",
      externalSkuId: "diamond-necklace-002",
      productName: "18K金钻石项链 0.18ct",
      category: "钻石饰品",
      brand: "周大福",
      sourceUrl: "https://demo.tmall.test/jewelry/diamond-necklace-002",
      rowIndex: 2,
      sales30d: 142,
      positiveRate: 0.964,
      stock: 42,
      originalPrice: 4999,
      lowestPrice30d: 4599,
      campaignPrice: 4399,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { diamond: "0.18ct", color: "H", clarity: "SI", certificate: "GIA摘要" },
    },
    {
      platform: "tmall",
      storeId: "ctf-flagship",
      externalSkuId: "sapphire-bracelet-003",
      productName: "天然蓝宝石手链 3.1ct",
      category: "彩宝饰品",
      brand: "周大福",
      sourceUrl: "https://demo.tmall.test/jewelry/sapphire-bracelet-003",
      rowIndex: 3,
      sales30d: 38,
      positiveRate: 0.931,
      stock: 9,
      originalPrice: 6999,
      lowestPrice30d: 6599,
      campaignPrice: 6299,
      joinedBrandDay: false,
      certificateStatus: "missing",
      raw: { gem: "sapphire", certificate: "缺少国检证书编号" },
    },
    {
      platform: "tmall",
      storeId: "ctf-flagship",
      externalSkuId: "gold-pendant-004",
      productName: "足金转运珠吊坠 2.8g",
      category: "黄金饰品",
      brand: "周大福",
      sourceUrl: "https://demo.tmall.test/jewelry/gold-pendant-004",
      rowIndex: 4,
      sales30d: 516,
      positiveRate: 0.976,
      stock: 18,
      originalPrice: 2199,
      lowestPrice30d: 1999,
      campaignPrice: 1899,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { material: "Au999", weight: "2.8g", stockRisk: "low" },
    },
    {
      platform: "jd",
      storeId: "jd-jewelry",
      externalSkuId: "pearl-earring-005",
      productName: "Akoya 海水珍珠耳钉 7-7.5mm",
      category: "珍珠饰品",
      brand: "京东珠宝",
      sourceUrl: "https://demo.jd.test/jewelry/pearl-earring-005",
      rowIndex: 5,
      sales30d: 206,
      positiveRate: 0.951,
      stock: 73,
      originalPrice: 1599,
      lowestPrice30d: 1399,
      campaignPrice: 1299,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { pearl: "Akoya", diameter: "7-7.5mm", certificate: "valid" },
    },
    {
      platform: "jd",
      storeId: "jd-jewelry",
      externalSkuId: "jade-bangle-006",
      productName: "冰糯种翡翠手镯 56圈口",
      category: "翡翠玉石",
      brand: "京东珠宝",
      sourceUrl: "https://demo.jd.test/jewelry/jade-bangle-006",
      rowIndex: 6,
      sales30d: 27,
      positiveRate: 0.887,
      stock: 5,
      originalPrice: 12800,
      lowestPrice30d: 11800,
      campaignPrice: 10999,
      joinedBrandDay: true,
      certificateStatus: "ambiguous",
      raw: { jade: "翡翠A货待复核", size: "56", joinedBrandDay: true },
    },
    {
      platform: "tmall",
      storeId: "ctf-flagship",
      externalSkuId: "platinum-chain-007",
      productName: "Pt950铂金锁骨链 3.6g",
      category: "铂金饰品",
      brand: "周大福",
      sourceUrl: "https://demo.tmall.test/jewelry/platinum-chain-007",
      rowIndex: 7,
      sales30d: 96,
      positiveRate: 0.948,
      stock: 64,
      originalPrice: 3299,
      lowestPrice30d: 3099,
      campaignPrice: 2999,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { material: "Pt950", weight: "3.6g" },
    },
    {
      platform: "jd",
      storeId: "jd-jewelry",
      externalSkuId: "gold-bar-008",
      productName: "投资金条 20g Au9999",
      category: "投资金",
      brand: "京东珠宝",
      sourceUrl: "https://demo.jd.test/jewelry/gold-bar-008",
      rowIndex: 8,
      sales30d: 61,
      positiveRate: 0.992,
      stock: 112,
      originalPrice: 12599,
      lowestPrice30d: 12380,
      campaignPrice: 12199,
      joinedBrandDay: false,
      certificateStatus: "valid",
      raw: { material: "Au9999", weight: "20g", priceLock: "enabled" },
    },
  ],
};

export const businessFoundationActivityRuleText = "618珠宝类目报名要求：库存不少于20件，好评率不少于92%，黄金/铂金/钻石/彩宝/翡翠商品必须具备有效证书；近30天最低价不得低于活动价；已参加互斥品牌日活动的SKU不得报名。";
