import type { AppPageDefinition } from '@/shared/types/app'

export const appPages: AppPageDefinition[] = [
  {
    key: 'dashboard',
    href: '/dashboard',
    title: 'Dashboard 总览',
    description: '查看主控台当前总体状态、风险摘要和人工介入入口。',
    navLabel: 'Dashboard',
    icon: '◫',
    category: 'primary',
  },
  {
    key: 'agent-chat',
    href: '/agent-chat',
    title: 'Agent Mission Chat',
    description: '承接目标输入、计划生成、系统工具调用、长任务执行和 Review Gate。',
    navLabel: 'Agent Mission',
    icon: '✦',
    category: 'primary',
  },
  {
    key: 'connectors',
    href: '/connectors',
    title: 'Connectors',
    description: '查看平台连接、插件采集边界和接入状态壳层。',
    navLabel: 'Connectors',
    icon: '⌁',
    category: 'primary',
  },
  {
    key: 'sku-health',
    href: '/sku-health',
    title: 'SKU 健康',
    description: '在列表与详情布局中承接 SKU 健康查询与诊断视图。',
    navLabel: 'SKU 健康',
    icon: '▦',
    category: 'primary',
  },
  {
    key: 'activities',
    href: '/activities',
    title: '活动规则与准入模拟',
    description: '承接规则录入、解析和模拟结果的页面结构。',
    navLabel: 'Activities',
    icon: '⎘',
    category: 'primary',
  },
  {
    key: 'reviews',
    href: '/reviews',
    title: 'Review 工作台',
    description: '承接人工审批门、证据查看与操作区。',
    navLabel: 'Reviews',
    icon: '✓',
    category: 'primary',
  },
  {
    key: 'reports',
    href: '/reports',
    title: '报告页',
    description: '承接报告预览、操作栏和证据关联摘要。',
    navLabel: 'Reports',
    icon: '☰',
    category: 'primary',
  },
  {
    key: 'workflows',
    href: '/workflows',
    title: 'Workflows',
    description: '承接工作流摘要时间线与步骤明细容器。',
    navLabel: 'Workflows',
    icon: '↻',
    category: 'secondary',
  },
]
